# Assignment 1
1. Generate an np array of (a) vector of lenght 50 (b) two dimension of shape 5x4. Both uniformly distributed between 0 and 1
2. Split the two dimension array in 1 above into three arrays taking the first two rows, follow by the next two rows and put the remaining row in another variable
3. Split the vector in 1 above into three arrays by taking the first 15, follow by the next 20 and the remaining into another variable.
4. Create a 4x5 array: 
   (a). Using manual method
   (b). Using randomly generated value between 0 and 1
   (c). Using array of ones

In [1]:
import numpy as np

In [2]:
xx=np.random.random(50)
xx

array([0.56273527, 0.97818327, 0.45103581, 0.87718523, 0.81799049,
       0.95606464, 0.63440703, 0.38803538, 0.05375667, 0.42150506,
       0.36838274, 0.72951483, 0.18039543, 0.78618543, 0.66790426,
       0.70038818, 0.47581936, 0.27068056, 0.66216616, 0.47653206,
       0.39476617, 0.15540709, 0.40230206, 0.3048804 , 0.52878032,
       0.23592673, 0.29428995, 0.12707268, 0.71226771, 0.85835079,
       0.3341543 , 0.3406857 , 0.16996743, 0.2515687 , 0.87650235,
       0.49290587, 0.11351763, 0.07176565, 0.12928988, 0.00238884,
       0.63043606, 0.46712565, 0.59147043, 0.90691169, 0.71779248,
       0.95816372, 0.95083136, 0.0059158 , 0.02074642, 0.99898613])

In [3]:
np.random.seed(0)
xy=np.random.random((5,4))
xy

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

In [4]:
first, second, third = np.vsplit(xy,[2,4])
print("the first split\n",first)
print("the second split\n",second)
print("the third split\n",third)

the first split
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]]
the second split
 [[0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]
the third split
 [[0.0202184  0.83261985 0.77815675 0.87001215]]


In [5]:
x1, x2, x3 = np.split(xx, (15,35))
print(x1,x2,x3)

[0.56273527 0.97818327 0.45103581 0.87718523 0.81799049 0.95606464
 0.63440703 0.38803538 0.05375667 0.42150506 0.36838274 0.72951483
 0.18039543 0.78618543 0.66790426] [0.70038818 0.47581936 0.27068056 0.66216616 0.47653206 0.39476617
 0.15540709 0.40230206 0.3048804  0.52878032 0.23592673 0.29428995
 0.12707268 0.71226771 0.85835079 0.3341543  0.3406857  0.16996743
 0.2515687  0.87650235] [0.49290587 0.11351763 0.07176565 0.12928988 0.00238884 0.63043606
 0.46712565 0.59147043 0.90691169 0.71779248 0.95816372 0.95083136
 0.0059158  0.02074642 0.99898613]


In [6]:
np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
np.random.random((4,5))

array([[0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ]])

In [8]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Assignment 2:
    #use us_births data to compute the following using np:
        #extract the year, gender and births column from the data
        #compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and std
        #compute the maximum births and minimum births
        #indicate the gender with minimum birth and maximum birth
        #indicate the year with minimum birth and maximum birth

In [1]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv('C:\\PythonClass\\Data Science\\Datasets\\us_births.csv')
df.head()

year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

In [11]:
#extract the year, gender and births column from the data
year = np.array(df['year'])
gender = df.gender.values
birth = df['births'].values
print("year\n",year,"\n")
print("gender\n",gender,"\n")
print("birth\n",birth)

year
 [1969 1969 1969 ... 2008 2008 2008] 

gender
 ['F' 'M' 'F' ... 'M' 'F' 'M'] 

birth
 [  4046   4440   4454 ... 165468 173215 181235]


In [12]:
#compute the aggregation of sum of total birth, sum of female birth and sum of male birth, 
# mean and standard deviation(std)
print("total births:   ", birth.sum())
print("mean birth:   ", birth.mean())
print('Sum of female birth:   ', np.sum(birth[np.equal(gender, 'F')]))
print('Sum of male birth:   ', np.sum(birth[np.equal(gender, 'M')]))
print("standard deviaton of total births:   ", birth.std())
print("Median of total births:   ", np.median(birth))

total births:    151774378
mean birth:    9762.293561458802
Sum of female birth:    74035823
Sum of male birth:    77738555
standard deviaton of total births:    28551.547532287397
Median of total births:    4814.0


In [13]:
#compute the maximum births and minimum births
print('max birth:   ', birth.max())
print('min birth:   ', birth.min())

max birth:    199622
min birth:    1


In [14]:
#indicate the gender with minimum birth and maximum birth
print('Gender with max birth:   ', gender[np.argmax(birth)])
print('Gender with min birth:   ', gender[np.argmin(birth)])

Gender with max birth:    M
Gender with min birth:    F


In [15]:
#indicate the year with minimum birth and maximum birth
print('Year with max birth:   ', year[np.argmax(birth)])
print('Year with min birth:   ', year[np.argmin(birth)])

Year with max birth:    2007
Year with min birth:    1975


# Assignment 3
Using the BicycleWeather.csv dataset perform the following operations:
    1. Extract the PRCP column from the pandas object.
    2. Using boolean functions/operators separate numbers from NAN
    3. Using boolean masking separate all zeros and non-zeros into different variables.
    4. From the variable holding non-zeros, multiply every values in the array with 100 and divid by 250
    5. Calculate the following:
        a. Median precip on rainy days
        b. Median precip on summer days 
        c. Maximum precip on summer days 
        d. Median precip on non-summer rainy days

In [2]:
bic = pd.read_csv('C:\\PythonClass\\Data Science\\Datasets\\BicycleWeather.csv')
bic

STATION                                STATION_NAME      DATE  \
0     GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120101   
1     GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120102   
2     GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120103   
3     GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120104   
4     GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120105   
...                 ...                                         ...       ...   
1335  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20150828   
1336  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20150829   
1337  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20150830   
1338  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20150831   
1339  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20150901   

      PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  ...  WT17  WT05  WT02  WT22  \
0        0     0     0   128    50    47   100  ... -9999 -9999 -9999 -9999   
1      109     0     0   106    28    45   180  ... -9999 -9999 -9999 -9999   
2        8     0     0   117    72    23   180  ... -9999 -9999 -9999 -9999   
3      203     0     0   122    56    47   180  ... -9999 -9999 -9999 -9999   
4       13     0     0    89    28    61   200  ... -9999 -9999 -9999 -9999   
...    ...   ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   
1335     5     0     0   233   156    26   230  ... -9999 -9999 -9999 -9999   
1336   325     0     0   222   133    58   210  ... -9999 -9999 -9999 -9999   
1337   102     0     0   200   128    47   200  ... -9999 -9999 -9999 -9999   
1338     0     0     0   189   161    58   210  ... -9999 -9999 -9999 -9999   
1339    58     0     0   194   139 -9999 -9999  ... -9999 -9999 -9999 -9999   

      WT04  WT13  WT16  WT08  WT18  WT03  
0    -9999 -9999 -9999 -9999 -9999 -9999  
1    -9999     1     1 -9999 -9999 -9999  
2    -9999 -9999     1 -9999 -9999 -9999  
3    -9999     1     1 -9999 -9999 -9999  
4    -9999 -9999     1 -9999 -9999 -9999  
...    ...   ...   ...   ...   ...   ...  
1335 -9999 -9999 -9999 -9999 -9999 -9999  
1336 -9999 -9999 -9999 -9999 -9999 -9999  
1337 -9999 -9999 -9999 -9999 -9999 -9999  
1338 -9999 -9999 -9999 -9999 -9999 -9999  
1339 -9999 -9999 -9999 -9999 -9999 -9999  

[1340 rows x 26 columns]

In [17]:
#  Extract the PRCP column from the pandas object.
prcp=bic['PRCP'].values
print(prcp)

[  0 109   8 ... 102   0  58]


In [93]:
# Using boolean functions/operators separate numbers from NAN
# no nan values
np.greater_equal(prcp, 0).size

1340

In [70]:
# Using boolean masking separate all zeros and non-zeros into different variables.
zero_val = prcp[np.equal(prcp, 0)]
non_zero = prcp[np.greater(prcp, 0)]
print('Zero values:  ', zero_val)
print('None Zero values:  ', non_zero)

Zero values:   [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0

In [72]:
#  From the variable holding non-zeros, multiply every values in the array with 100 and divid by 250
(non_zero*100)/250

array([ 43.6,   3.2,  81.2,   5.2,  10. ,  17.2,   4. ,  16.4,  21.2,
        10. ,  32.4,  79.2,  60.8,  54. ,  12. ,  24.4,  34.4,  32.4,
        19.2, 110.8,  14.4,   7.2,  54. ,   1.2,  11.2,  10. ,  10. ,
         3.2,   4. ,  45.6,  10. ,   7.2,  69.2,  25.6,  12. ,   3.2,
        34.4,  45.6,   5.2,  14.4,   3.2,   8. ,  27.6,   2. ,  14.4,
        41.6,  54.8,  77.2,  37.6,  34.4,  95.6,  33.6,  37.6,  14.4,
         8. ,  14.4,   5.2,  16.4,  19.2,   5.2, 109.6,  22.4,  52.8,
         6. ,   6. ,  18.4,   1.2,   9.2,   2. ,  32.4,   7.2,   7.2,
        43.6,  26.4,  17.2,  42.8,  15.2,   3.2,  17.2,  17.2,   2. ,
         2. ,  74. ,   7.2,  25.6,  56. ,  24.4,   1.2,   1.2,  15.2,
        26.4,   1.2,   5.2,  64. ,  66. ,   6. ,   3.2,  12. ,   4. ,
        62.8,  34.4,   2. ,   1.2,  12. ,   8. ,  23.2,   6. ,   2. ,
         1.2,  60.8,   4. ,   1.2,   1.2,   1.2,   8. ,  19.2,  66. ,
        31.6,  83.2,  19.2,   2. ,  25.6,  35.6,  28.4,   6. ,  92.4,
        24.4,  43.6,

In [81]:
# Generating summer days 
summer = (np.arange(556)-278<90) & (np.arange(556)-278>0)
summer_prcp = non_zero[summer]
summer_prcp

array([  3,  36, 135,  28,  20,  10, 434, 168, 185,  79,  53,   8,  41,
         5,  69,  10,  91,  10,  18,   5,   3,  13, 127,   5,  25,  38,
       300,  18,  41,  13,  30,  53, 262,  10,   5,  23,  30,  46,  69,
         5,  13,   3,  13,  56,  56, 107,  15,   3,   3,   5,  41,  15,
         3, 122,  97,  58,  43, 213,  15,   5,  89, 216,  23,  20,  51,
         5, 183, 170,  46,  18,  94, 117, 264, 145, 152,  10,  30,  28,
        25,  61, 130,   3,   5, 191, 107, 165, 467,  30, 323], dtype=int64)

In [87]:
# 5. Calculate the following: a. Median precip on rainy days b. Median precip on summer days 
# c. Maximum precip on summer days d. Median precip on non-summer rainy days
print("Median precip on rainy days in 2012: ", np.median([non_zero]))
print("Median precip on summer days in 2012: ", np.median([summer_prcp]))
print("Max precip on rainy days in 2012: ", np.max([summer_prcp]))
print("Median precip on non-summer rainy days: ", np.median(non_zero[~summer]))

Median precip on rainy days in 2012:  38.0
Median precip on summer days in 2012:  36.0
Max precip on rainy days in 2012:  467
Median precip on non-summer rainy days:  38.0
